@net_basic_todo_HostAddress = http://localhost:3001

GET {{net_basic_todo_HostAddress}}/api/health
Accept: application/json

###

# 1. Get all todos (seed has 3 todos)
GET {{net_basic_todo_HostAddress}}/api/todos
Accept: application/json

###

# 2. Get existing todo by id (id = 1)
GET {{net_basic_todo_HostAddress}}/api/todos/1
Accept: application/json

###

# 3. Create a new todo (will get id = 4)
POST {{net_basic_todo_HostAddress}}/api/todos
Content-Type: application/json

{
  "title": "Build CRUD endpoints in ASP.NET Core",
  "isDone": false
}

###

# 4. Update an existing todo (id = 1)
PUT {{net_basic_todo_HostAddress}}/api/todos/1
Content-Type: application/json

{
  "title": "Learn C# and .NET (Updated!)",
  "isDone": true
}

###

# 5. Update a non-existing todo (returns 404)
PUT {{net_basic_todo_HostAddress}}/api/todos/999
Content-Type: application/json

{
  "title": "Ghost todo",
  "isDone": false
}

###

# 6. Delete an existing todo (id = 2)
DELETE {{net_basic_todo_HostAddress}}/api/todos/2

###

# 7. Delete the same todo again (returns 404)
DELETE {{net_basic_todo_HostAddress}}/api/todos/2

###

# 8. Get all todos at the end to see the final state
GET {{net_basic_todo_HostAddress}}/api/todos
Accept: application/json

###
